version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    container_name: book_management
    command: ["python", "app/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGODB_HOST=db
      - MONGODB_PORT=27017
      - MONGODB_NAME=bookdb

volumes:
  mongo_data:
